SELECT * FROM Sheet1$

----Let's get the total number of bookings in the dataset

SELECT COUNT([Booking ID]) AS no_of_bookings
FROM Sheet1$


--------What is the average booking price across all hotels?

SELECT ROUND(AVG([Booking Price(SGD)]),1) AS Avg_booking_price
FROM Sheet1$


-----Which destination country received the highest number of bookings?

SELECT TOP 1 [Destination Country],
     COUNT([Booking ID]) AS Destination_Country_withhighest_noof_booking
     FROM Sheet1$
     GROUP BY [Destination Country]
     ORDER BY Destination_Country_withhighest_noof_booking desc;


----How many bookings were made by customers of each gender?

SELECT [Gender], COUNT([Booking ID]) AS Gender_based_booking
FROM Sheet1$
GROUP BY [Gender]


------What is the total revenue generated by the hotels?

SELECT ROUND(SUM([Booking Price(SGD)]),1) AS Total_revenue
FROM Sheet1$


-----Which TOP 5 age groupS contributed the most to the total revenue?

SELECT TOP 5 [Age], 
    ROUND(SUM([Booking Price(SGD)]),1) AS Agegroup_withmost_revenue
    FROM Sheet1$
    GROUP BY [Age]
    ORDER BY Agegroup_withmost_revenue DESC


------Which month had the highest number of bookings?

SELECT TOP 1 MONTH([Date of Booking]), 
COUNT([Booking ID]) AS month_with_highestbooking
FROM Sheet1$
GROUP BY MONTH([Date of Booking])
ORDER BY month_with_highestbooking DESC


------How many bookings were made using each payment mode?

SELECT [Payment Mode], COUNT([Booking ID]) AS Paymentmode_based_booking
FROM Sheet1$
GROUP BY [Payment Mode]
ORDER BY Paymentmode_based_booking DESC


-----How many bookings received discounts greater than 10%

SELECT COUNT([Booking ID]) AS No_of_bookingswith_greaterthan_10percent_discount
FROM Sheet1$
WHERE [Discount] > 0.1;


-----Which bank was used for the highest number of bookings?

SELECT TOP 1 [Bank Name], COUNT([Booking ID]) AS Bank_payment
FROM Sheet1$
GROUP BY [Bank Name]
ORDER BY Bank_payment DESC


------Which 10 destination country had the highest total revenue, and what are the ratings of the hotels in that country?

SELECT TOP 10 [Destination Country],SUM([Booking Price(SGD)]) AS Total_revenue, 
     [Hotel Name], [Hotel Rating]
	 FROM Sheet1$
	 GROUP BY [Destination Country], [Hotel Name], [Hotel Rating]
	 ORDER BY Total_revenue DESC


------How many bookings were made by customers from each origin country, and what is the average hotel rating for each country?

SELECT [Origin Country], COUNT([Booking ID]) AS Total_bookings, 
     ROUND(AVG([Hotel Rating]),1) AS Avg_rating
	 FROM Sheet1$
	 GROUP BY [Origin Country], [Hotel Rating]
	 ORDER BY Total_bookings, Avg_rating DESC


----For each payment mode, what is the total profit margin earned by hotels?

SELECT [Payment Mode], 
ROUND(SUM([Profit Margin]),1) AS Profit_margin_basedon_Paymentmode
FROM Sheet1$
GROUP BY [Payment Mode]
ORDER BY Profit_margin_basedon_Paymentmode DESC


----What is the average booking price for customers from each state, considering only bookings with a discount?

SELECT [State], ROUND(AVG([Booking Price(SGD)]),1) AS Avg_booking_price  
	 FROM Sheet1$
	 WHERE [Discount] > 0
	 GROUP BY [State]
	 ORDER BY Avg_booking_price DESC


----What is the total number of bookings made for each hotel, and what is the average age of customers for each hotel?

SELECT [Hotel Name], COUNT([Booking ID]) AS total_bookings,
     ROUND(AVG([Age]),0) AS Avg_ageof_customers  
	 FROM Sheet1$
	 GROUP BY [Hotel Name]
	 ORDER BY total_bookings, Avg_ageof_customers DESC



-----Which hotel has the highest total revenue, and what is the average age of its customers?

SELECT TOP 1 [Hotel Name], 
      ROUND(SUM([Booking Price(SGD)]),1) AS Total_revenue,
      ROUND(AVG([Age]),0) AS Avg_ageof_each_customer
      FROM Sheet1$
      GROUP BY [Hotel Name]
     ORDER BY Total_revenue, Avg_ageof_each_customer DESC



 ----Which country do most of the customers come from?

 SELECT TOP 1 [Origin Country], COUNT([Booking ID]) AS Total_Countrybookings 
	 FROM Sheet1$
	 GROUP BY [Origin Country]
	 ORDER BY Total_Countrybookings DESC



---------Which two countries and cities is most of the customers going to?

 SELECT TOP 2 [Destination Country], [Destination City], 
     COUNT([Booking ID]) AS Total_bookings 
	 FROM Sheet1$
	 GROUP BY [Destination Country], [Destination City]
	 ORDER BY Total_bookings DESC